use_frameworks!

platform :ios, '9.0'

target 'JCMaNongChenZaiTest_Example' do
  pod 'JCMaNongChenZaiTest', :path => '../'

  target 'JCMaNongChenZaiTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
